### PR TITLE
fix year picker

### LINKED ISSUE #44: add input box that checks that input contains only integers
I think this will error on failure to parse.  I think instead we may want to just strip out any non-number characters first, and then "parse" it (no need for Funtypes if we don't want, as at that point a simple cast would do the trick).  This way if the user copy/pastes a year and it has leading/trailing spaces, commas, etc. it will "do the right thing".  Since this function sets `year.value` at the end, it will update the input and strip out any wrong characters as they are typed.

_Originally posted by @MicahZoltu in https://github.com/DarkFlorist/PetalLock/pull/36#discussion_r1758639160_

### PR DESCRIPTION
**Pull request by KillariDev**
fix https://github.com/DarkFlorist/PetalLock/issues/44

### CODE REVIEW

File: app/ts/components/YearPicker.tsx [hunk 1]
```diff
@@ -1,34 +1,39 @@
...
-				maxlength = { 4 }
-				type = 'text'
-				pattern = '\d*'
-				value = { year.value }
-				onInput = { e => setYear(e.currentTarget.value) }
-			/>
-			<div class = 'year-selector-counter-num'>{ year }</div>
+
+	const handleInputChange = (e: Event) => {
+		const inputValue = (e.target as HTMLInputElement).value
```
Comment (MicahZoltu) [inline app/ts/components/YearPicker.tsx]: Three things here:
1. I recommend correctly typing the event so you don't have to cast.
2. I recommend using a more verbose variable name instead of `e`.
3. I am pretty sure you want `currentTarget` and not `target`.  You may want to investigate to verify though.
```suggestion
	const handleInputChange = (event: JSX.TargetedEvent<HTMLInputElement, Event>) => {
		const inputValue =event.currentTarget.value
```

File: app/ts/components/YearPicker.tsx [hunk 2]
```diff
@@ -1,34 +1,39 @@
...
+
+	return (
+		<div class = 'year-selector'>
+			<div class = 'year-selector-button year-selector-button-decrement' onClick = { decrement }>&ndash;</div>
+			<div class = 'year-selector-counter'>
+				<input
+					class = 'year-selector-counter-input'
+					maxLength = { 4 }
+					type = 'text'
+					value = { year.value }
```
Comment (MicahZoltu) [inline app/ts/components/YearPicker.tsx]: In general, it is better to provide `Signal` objects rather than the `.value` on them to components.  This minimizes re-renders and is generally a good habit to follow.
```suggestion
					value = { year }
```

File: app/ts/components/YearPicker.tsx [hunk 3]
```diff
@@ -1,34 +1,39 @@
...
+					onInput = { handleInputChange }
+				/>
+				<div class = 'year-selector-counter-num'>{ year.value }</div>
```
Comment (MicahZoltu) [inline app/ts/components/YearPicker.tsx]:
```suggestion
				<div class = 'year-selector-counter-num'>{ year }</div>
```

**Review by MicahZoltu — APPROVED** [review]
Approved pending changing the suggested things or putting forward an argument for why they shouldn't be applied.
